name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # todos os dias à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: matheuspereira35
          outputs: |
            dist/github-contribution-grid-snake.svg
      - name: Commit animation
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
